### ISSUE TITLE
Crashes once you start the first combat

### ISSUE THREAD

**Issue by Chickdeez** [yhrcyt/StS-TheWarriorMod#1]

**Comment by Chickdeez** [comment]
Unfortunately I don't know how to get such information. I don't get any error messages nor anything else. It just quits the program and same happens if I try continue the run. Sorry for not helping much.

**Comment by yhrcyt** [comment]
the latest game log is located in
(GAME FOLDER)\sendToDevs\logs\SlayTheSpire.log

**Comment by Chickdeez** [comment]
I got it working. The problem occurred when I had other mods on at the same time. When I used the base + warrior it works like a charm.
