### ISSUE TITLE
Dagger-Thrust appeared as its own broken card

### ISSUE THREAD

**Issue by SilentJ28** [yhrcyt/StS-TheWarriorMod#10]
I didn't crash but hit a similar issue to the addtional commment in https://github.com/yhrcyt/StS-TheWarriorMod/issues/8 where a Thrust appeared in my hand as a stand alone card. I started a combo with Sword (Thrust) then Dagger (Thrust) then the stand alone thrust floated but my only option was finish combo and the stand alone Thrust went to discard.

The log is filled with Errors from your logging about the fact that stand alone thrust was unexpected.

"03:07:07.097 INFO thewarrior.TheWarriorMod> TipHelperPatch: Why there's no sub card to render?"
"03:07:12.918 INFO thewarrior.TheWarriorMod> Error: trying to render combo type tip for a card that is not a weapon of The Warrior"
[SlayTheSpire.log](https://github.com/yhrcyt/StS-TheWarriorMod/files/2481263/SlayTheSpire.log)

Here is a picture of my discard pile that shows the Thrust subcard of the dagger as it's own card
![warriorthrust](https://user-images.githubusercontent.com/40654703/46990554-ae32f300-d0b6-11e8-8b1c-29644fd8b83b.png)

**Comment by yhrcyt** [comment]
this mod is soooo broken
problem located
a hotfix will be released asap
