### ISSUE TITLE
Double combo power null pointer exception if you use a second combo after the first one.

### ISSUE THREAD

**Issue by 5m1l35** [yhrcyt/StS-TheWarriorMod#13]
If you use combo power and a combo and then execute another combo after it in the same turn it tries to execute the combo power again and returns a null pointer. Which is then passed along and creates many problems.
[SlayTheSpire_201810172003_1.log](https://github.com/yhrcyt/StS-TheWarriorMod/files/2492554/SlayTheSpire_201810172003_1.log)

**Comment by yhrcyt** [comment]
thanks for reporting
gonna fix it soon

**Comment by 5m1l35** [comment]
Np

**Comment by 5m1l35** [comment]
correct me if I am wrong very pleb at programing but wouldn't java.util.ArrayList.clear(DoubleComboPower.doubleComboAction) at line 220 in combo action fix this?

**Comment by 5m1l35** [comment]
the code would not run when the second combo is executed as the if statement would definitely come up false tho I think it will generate problems because the object would have never been created as there are nothing calling that statment so put it in the if statement at the end

**Comment by 5m1l35** [comment]
again major pleb

**Comment by 5m1l35** [comment]
sorry for bothering you I will leave the patching and fixing to the person that actually made the code.

**Comment by yhrcyt** [comment]
nevermind. I'm working on Ascension Minus mod and will release it very soon (It's actually already done). once I've finished releasing I'll patch this bug asap.

**Comment by yhrcyt** [comment]
fixed
