### ISSUE TITLE
Game Crashed when tried to start the game

### ISSUE THREAD

**Issue by fkinghatesigningup** [yhrcyt/StS-TheWarriorMod#2]
Before reporting this bug, please check your mod version. All of your mods need to be up-to-date.

**Crash Reports**
If the game crashed because of this bug, please copy the crash report or game log here.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]

**Additional context**

**Comment by yhrcyt** [comment]
any further information please? e.g. what mod are you using?

**Comment by fkinghatesigningup** [comment]
Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: java.lang.NoClassDefFoundError: com/megacrit/cardcrawl/ui/panels/energyorb/EnergyOrbInterface
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:133)
Caused by: java.lang.NoClassDefFoundError: com/megacrit/cardcrawl/ui/panels/energyorb/EnergyOrbInterface
	at thewarrior.TheWarriorMod.receiveEditCharacters(TheWarriorMod.java:76)
	at basemod.BaseMod.publishEditCharacters(BaseMod.java:2405)
	at basemod.EditCharactersInit.receivePostInitialize(EditCharactersInit.java:9)
	at basemod.BaseMod.publishPostInitialize(BaseMod.java:2162)
	at basemod.patches.com.megacrit.cardcrawl.core.CardCrawlGame.PostInitializeHook.Postfix(PostInitializeHook.java:9)
	at com.megacrit.cardcrawl.core.CardCrawlGame.create(CardCrawlGame.java:323)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:149)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)
Caused by: java.lang.ClassNotFoundException: com.megacrit.cardcrawl.ui.panels.energyorb.EnergyOrbInterface
	at com.evacipated.cardcrawl.modthespire.MTSClassLoader.findClass(MTSClassLoader.java:82)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at com.evacipated.cardcrawl.modthespire.MTSClassLoader.loadClass(MTSClassLoader.java:65)
	... 8 more04:38:42.305 INFO helpers.File> Successfully saved file=C:\Program Files (x86)\Steam\steamapps\common\SlayTheSpire\preferences\STSUnlocks
04:38:42.306 INFO helpers.FileSaver> Dequeue: qsize=21 file=preferences\STSUnlocks
04:38:42.306 INFO helpers.File> Attempting to save file=C:\Program Files (x86)\Steam\steamapps\common\SlayTheSpire\preferences\STSUnlocks
04:38:42.318 INFO helpers.File> Successfully saved file=C:\Program Files (x86)\Steam\steamapps\common\SlayTheSpire\preferences\STSUnlocks
04:38:42.322 INFO helpers.FileSaver> Dequeue: qsize=20 file=preferences\STSUnlocks
04:38:42.322 INFO helpers.File> Attempting to save file=C:\Program Files (x86)\Steam\steamapps\common\SlayTheSpire\preferences\STSUnlocks
04:38:42.334 INFO helpers.File> Successfully saved file=C:\Program Files (x86)\Steam\steamapps\common\SlayTheSpire\preferences\STSUnlocks
04:38:42.343 INFO helpers.FileSaver> Dequeue: qsize=19 file=preferences\STSUnlocks
04:38:42.343 INFO helpers.File> Attempting to save file=C:\Program Files (x86)\Steam\steamapps\common\SlayTheSpire\preferences\STSUnlocks
04:38:42.356 INFO helpers.File> Successfully saved file=C:\Program Files (x86)\Steam\steamapps\common\SlayTheSpire\preferences\STSUnlocks
04:38:42.359 INFO helpers.FileSaver> Dequeue: qsize=18 file=preferences\STSUnlocks
04:38:42.360 INFO helpers.File> Attempting to save file=C:\Program Files (x86)\Steam\steamapps\common\SlayTheSpire\preferences\STSUnlocks
04:38:42.373 INFO helpers.File> Successfully saved file=C:\Program Files (x86)\Steam\steamapps\common\SlayTheSpire\preferences\STSUnlocks
04:38:42.375 INFO helpers.FileSaver> Dequeue: qsize=17 file=preferences\STSUnlocks
04:38:42.375 INFO helpers.File> Attempting to save file=C:\Program Files (x86)\Steam\steamapps\common\SlayTheSpire\preferences\STSUnlocks
04:38:42.389 INFO helpers.File> Successfully saved file=C:\Program Files (x86)\Steam\steamapps\common\SlayTheSpire\preferences\STSUnlocks
04:38:42.389 INFO helpers.FileSaver> Dequeue: qsize=16 file=preferences\STSUnlocks
04:38:42.389 INFO helpers.File> Attempting to save file=C:\Program Files (x86)\Steam\steamapps\common\SlayTheSpire\preferences\STSUnlocks
04:38:42.402 INFO helpers.File> Successfully saved file=C:\Program Files (x86)\Steam\steamapps\common\SlayTheSpire\preferences\STSUnlocks
04:38:42.403 INFO helpers.FileSaver> Dequeue: qsize=15 file=preferences\STSUnlocks
04:38:42.403 INFO helpers.File> Attempting to save file=C:\Program Files (x86)\Steam\steamapps\common\SlayTheSpire\preferences\STSUnlocks
04:38:42.417 INFO helpers.File> Successfully saved file=C:\Program Files (x86)\Steam\steamapps\common\SlayTheSpire\preferences\STSUnlocks
04:38:42.418 INFO helpers.FileSaver> Dequeue: qsize=14 file=preferences\STSUnlocks
04:38:42.418 INFO helpers.File> Attempting to save file=C:\Program Files (x86)\Steam\steamapps\common\SlayTheSpire\preferences\STSUnlocks
04:38:42.433 INFO helpers.File> Successfully saved file=C:\Program Files (x86)\Steam\steamapps\common\SlayTheSpire\preferences\STSUnlocks
04:38:42.433 INFO helpers.FileSaver> Dequeue: qsize=13 file=preferences\STSUnlocks
04:38:42.433 INFO helpers.File> Attempting to save file=C:\Program Files (x86)\Steam\steamapps\common\SlayTheSpire\preferences\STSUnlocks
04:38:42.448 INFO helpers.File> Successfully saved file=C:\Program Files (x86)\Steam\steamapps\common\SlayTheSpire\preferences\STSUnlocks
04:38:42.448 INFO helpers.FileSaver> Dequeue: qsize=12 file=preferences\STSUnlocks
04:38:42.448 INFO helpers.File> Attempting to save file=C:\Program Files (x86)\Steam\steamapps\common\SlayTheSpire\preferences\STSUnlocks
04:38:42.463 INFO helpers.File> Successfully saved file=C:\Program Files (x86)\Steam\steamapps\common\SlayTheSpire\preferences\STSUnlocks
04:38:42.463 INFO helpers.FileSaver> Dequeue: qsize=11 file=preferences\STSUnlocks
04:38:42.463 INFO helpers.File> Attempting to save file=C:\Program Files (x86)\Steam\steamapps\common\SlayTheSpire\preferences\STSUnlocks
04:38:42.478 INFO helpers.File> Successfully saved file=C:\Program Files (x86)\Steam\steamapps\common\SlayTheSpire\preferences\STSUnlocks
04:38:42.478 INFO helpers.FileSaver> Dequeue: qsize=10 file=preferences\STSUnlocks
04:38:42.478 INFO helpers.File> Attempting to save file=C:\Program Files (x86)\Steam\steamapps\common\SlayTheSpire\preferences\STSUnlocks
04:38:42.493 INFO helpers.File> Successfully saved file=C:\Program Files (x86)\Steam\steamapps\common\SlayTheSpire\preferences\STSUnlocks
04:38:42.493 INFO helpers.FileSaver> Dequeue: qsize=9 file=preferences\STSUnlocks
04:38:42.493 INFO helpers.File> Attempting to save file=C:\Program Files (x86)\Steam\steamapps\common\SlayTheSpire\preferences\STSUnlocks
04:38:42.507 INFO helpers.File> Successfully saved file=C:\Program Files (x86)\Steam\steamapps\common\SlayTheSpire\preferences\STSUnlocks
04:38:42.508 INFO helpers.FileSaver> Dequeue: qsize=8 file=preferences\STSUnlocks
04:38:42.508 INFO helpers.File> Attempting to save file=C:\Program Files (x86)\Steam\steamapps\common\SlayTheSpire\preferences\STSUnlocks
04:38:42.562 INFO helpers.File> Successfully saved file=C:\Program Files (x86)\Steam\steamapps\common\SlayTheSpire\preferences\STSUnlocks
04:38:42.563 INFO helpers.FileSaver> Dequeue: qsize=7 file=preferences\STSUnlocks
04:38:42.564 INFO helpers.File> Attempting to save file=C:\Program Files (x86)\Steam\steamapps\common\SlayTheSpire\preferences\STSUnlocks
04:38:42.596 INFO helpers.File> Successfully saved file=C:\Program Files (x86)\Steam\steamapps\common\SlayTheSpire\preferences\STSUnlocks
04:38:42.597 INFO helpers.FileSaver> Dequeue: qsize=6 file=preferences\STSUnlocks
04:38:42.597 INFO helpers.File> Attempting to save file=C:\Program Files (x86)\Steam\steamapps\common\SlayTheSpire\preferences\STSUnlocks
04:38:42.617 INFO helpers.File> Successfully saved file=C:\Program Files (x86)\Steam\steamapps\common\SlayTheSpire\preferences\STSUnlocks
04:38:42.618 INFO helpers.FileSaver> Dequeue: qsize=5 file=preferences\STSUnlocks
04:38:42.618 INFO helpers.File> Attempting to save file=C:\Program Files (x86)\Steam\steamapps\common\SlayTheSpire\preferences\STSUnlocks
04:38:42.633 INFO helpers.File> Successfully saved file=C:\Program Files (x86)\Steam\steamapps\common\SlayTheSpire\preferences\STSUnlocks
04:38:42.633 INFO helpers.FileSaver> Dequeue: qsize=4 file=preferences\STSUnlocks
04:38:42.633 INFO helpers.File> Attempting to save file=C:\Program Files (x86)\Steam\steamapps\common\SlayTheSpire\preferences\STSUnlocks
04:38:42.648 INFO helpers.File> Successfully saved file=C:\Program Files (x86)\Steam\steamapps\common\SlayTheSpire\preferences\STSUnlocks
04:38:42.649 INFO helpers.FileSaver> Dequeue: qsize=3 file=preferences\STSUnlocks
04:38:42.649 INFO helpers.File> Attempting to save file=C:\Program Files (x86)\Steam\steamapps\common\SlayTheSpire\preferences\STSUnlocks
04:38:42.664 INFO helpers.File> Successfully saved file=C:\Program Files (x86)\Steam\steamapps\common\SlayTheSpire\preferences\STSUnlocks
04:38:42.665 INFO helpers.FileSaver> Dequeue: qsize=2 file=preferences\STSUnlocks
04:38:42.665 INFO helpers.File> Attempting to save file=C:\Program Files (x86)\Steam\steamapps\common\SlayTheSpire\preferences\STSUnlocks
04:38:42.704 INFO helpers.File> Successfully saved file=C:\Program Files (x86)\Steam\steamapps\common\SlayTheSpire\preferences\STSUnlocks
04:38:42.704 INFO helpers.FileSaver> Dequeue: qsize=1 file=preferences\STSUnlocks
04:38:42.704 INFO helpers.File> Attempting to save file=C:\Program Files (x86)\Steam\steamapps\common\SlayTheSpire\preferences\STSUnlocks
04:38:42.755 INFO helpers.File> Successfully saved file=C:\Program Files (x86)\Steam\steamapps\common\SlayTheSpire\preferences\STSUnlocks
04:38:42.756 INFO helpers.FileSaver> Dequeue: qsize=0 file=preferences\STSUnlocks
04:38:42.757 INFO helpers.File> Attempting to save file=C:\Program Files (x86)\Steam\steamapps\common\SlayTheSpire\preferences\STSUnlocks
04:38:42.812 INFO helpers.File> Successfully saved file=C:\Program Files (x86)\Steam\steamapps\common\SlayTheSpire\preferences\STSUnlocks

**Comment by fkinghatesigningup** [comment]
Mode the Spire 3.3.0

**Comment by fkinghatesigningup** [comment]
Just base mod and warrior

**Comment by yhrcyt** [comment]
Can you start the game using mod the spire without any mods? It looks like there's something missing in your base game.

**Comment by fkinghatesigningup** [comment]
yea i can start it without any mods, which version of mod the spire and base mod should i use?

**Comment by yhrcyt** [comment]
newest version

**Comment by fkinghatesigningup** [comment]
yea not sure what happened i can't load anything now on newest versions, i get the following:

Running with debug mode turned ON...

ModVersion Info:
 - Java version (1.8.0_161)
 - Slay the Spire (10-04-2018)
 - ModTheSpire (3.3.0)
Mod list:
 - basemod (4.0.0)
 - TheWarrior (0.0.2)

Begin patching...
Finding core patches...
Finding patches...
java.lang.NoSuchMethodException: Patch basemod.patches.com.megacrit.cardcrawl.screens.charSelect.CharacterOption.CtorSwitch:
No method [<ctor>(java.lang.String, com.megacrit.cardcrawl.characters.AbstractPlayer, java.lang.String, java.lang.String)] found on
class [com.megacrit.cardcrawl.screens.charSelect.CharacterOption]
	at com.evacipated.cardcrawl.modthespire.Patcher.injectPatches(Patcher.java:271)
	at com.evacipated.cardcrawl.modthespire.Patcher.injectPatches(Patcher.java:179)
	at com.evacipated.cardcrawl.modthespire.Loader.runMods(Loader.java:191)
	at com.evacipated.cardcrawl.modthespire.ui.ModSelectWindow.lambda$null$1(ModSelectWindow.java:272)
	at java.lang.Thread.run(Unknown Source)

**Comment by fkinghatesigningup** [comment]
eh it's the slay the spire version isn't it...

**Comment by yhrcyt** [comment]
yeah you didn't update your slay the spire...
can I close this issue now?

**Comment by fkinghatesigningup** [comment]
yea my bad thanks for all your help
