### ISSUE TITLE
Preview rendering issue with Sword

### ISSUE THREAD

**Issue by SilentJ28** [yhrcyt/StS-TheWarriorMod#5]
Weird rendering issue for the 3rd option when hovering over Sword.
This wasn't happening in the earlier fight so not sure what is different now.

![warrior](https://user-images.githubusercontent.com/40654703/46914359-f6d09c00-cf50-11e8-841e-9a3672386dee.png)

**Comment by yhrcyt** [comment]
game log please?

**Comment by SilentJ28** [comment]
[SlayTheSpire.log](https://github.com/yhrcyt/StS-TheWarriorMod/files/2476214/SlayTheSpire.log)

**Comment by yhrcyt** [comment]
sorry, the game log is not helpful at all.
does this happen very often?
when does it usually happen?

**Comment by yhrcyt** [comment]
maybe it's because of other mods. they might override the render card method, and can cause compatibility issues.

**Comment by SilentJ28** [comment]
Yeah I couldn't see anything in the log. This is the only time I have seen this issue and it was fine in earlier fights. Possibly fine earlier in this same fight.

**Comment by yhrcyt** [comment]
can you send me your mod list?

**Comment by SilentJ28** [comment]
BaseMod
StSLib
Friendly Minions
Always Whale
Colored Map
Replay the Spire
Hubris
Blakk Mod
Infinite Spire
The Mystic
Beaked the Cultist
The Disciple
Mad Scientist
The Construct
Blackbeard
Warrior

**Comment by yhrcyt** [comment]
Thank you for reporting the problem. I'm pretty sure it's not my mod's problem, but I will try to find the problem and contact that mod author.
