### ISSUE TITLE
Explanation of Combo Mechanic

### ISSUE THREAD

**Issue by ongteckwu** [yhrcyt/StS-TheWarriorMod#6]
Hi Yhrcyt,

Really appreciate you work on this mod. Just have one small request: can you explain how the combo thing works? Either in the readme or in the game. I cant seem to figure it out. Sometimes I get the option of creating a combo, and sometimes I don't. Would be great if the mechanics can be clarified.

Also, would be great if you can add to the readme the list of effects you have implemented, as I am not sure how to create synergies with Speed, Bleeding, Dazed etc. Would be great to be able to plan ahead with the synergies in mind.

**Comment by yhrcyt** [comment]
First of all, thank you.
I thought I already explained them in the game. You can just hover over the cards to see what they do.
Do you use keyboard or controller to play this game so you can't see them?

Anyways, thank you for your advice. I will create a wiki page soon.
