### ISSUE TITLE
The card "Sword" doesn't have supporting text telling what the 3 chosen cards can combo with.

### ISSUE THREAD

**Issue by fkinghatesigningup** [yhrcyt/StS-TheWarriorMod#7]

**Comment by fkinghatesigningup** [comment]
Not exclusive to sword also happens with claw and strong axe

**Comment by yhrcyt** [comment]
There's a problem though. Card doesn't combo based on card but on attack type. Highlight card might not be a good idea, I think. But I will try to create my own system that explains combo type thing.
